import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/app/styles/globals.css";
import { ThemeProvider } from "next-themes";
import styles from "./layout.module.scss";

const nunito = Nunito({
  subsets: ["latin", "cyrillic"],
  variable: "--nunito",
});

export const metadata: Metadata = {
  title: "LSM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="light dark" />
        <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#000000" media="(prefers-color-scheme: dark)" />
      </head>
      <body className={nunito.variable}>
        <ThemeProvider
					disableTransitionOnChange={false}
          attribute="data-theme"
          enableSystem={true}
          storageKey="lms-theme"
        >
          <div className={styles.layout}>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
